from enum import IntEnum


class CodeState(IntEnum):
    INI_FLAG= 0
    VALID_POINT= 1
    PACKED_POINT =2
    DUPLICATE_CODE_POINT=3
    ERROR_WEEKNUM_CODE_POINT= 4
    UNTEST_CODE_POINT= 5
    ERROR_FIXED_CODE_POINT= 6
    ERROR_CODE_LENGTH= 7
    SAVE_ERROR_POINT= 8

class BoxState(IntEnum):
    DUPLICATE_BOX_NUMBER=1
    UNFILLED_BOX_NUMBER=0
    UNDEFINED_BOX_NUMBER=2
    VALID_BOX_NUMBER=3

class InputDataState(IntEnum):
    INPUTDATA_VALID=0
    INPUTDATA_INVALID=1