code: '1255'
layerNumEachBox: 0
adapterNumEachPoint: 0
numAdapterEachLine: 1
pointNumEachLine: 0
model: '123'
boxNumber: '3211'
weekNum: 0
weekNumPosition: 2
lineNumEachLayer: 0
adapterNumEachLayer: 2
packedNum: 0
maxPackNum: 0
fixCode: 0A001-00446200023B
codeLength: 23
boxNumberLength: 4
isCheckBoxNumberLength: true
isCheckCodeLength: false
isCheckFixCode: false
isCheckUntest: true
isCheckDuplicate: true
isCheckWeekNum: true
codeState: ERROR_LENGTH_CODE
serialNumber: C_2
isCommonPackMode: true
dayPackedAdapterNum: 14
dayPackedBoxNum: 5
dayErrorCodeNum: 0
dayUntestCodeNum: 0
dayDuplicateCodeNum: 0
codeRange: '1212'
